import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "People at Work closes on 2 October. Your obligations don't. | HowsWork",
  alternates: { canonical: "/articles/people-at-work-closing" },
};

export default function PeopleAtWorkClosing() {
  return (
    <main className="pt-14">
      <article className="mx-auto max-w-4xl px-6 pt-24 sm:pt-32 lg:px-8">
        <h2 className="mt-4 text-4xl font-semibold tracking-tight text-pretty text-gray-900 sm:text-5xl dark:text-white">
          People at Work closes on 2 October. Your obligations don&apos;t.
        </h2>

        <figure className="mt-10">
          <Image
            src="/img/articles/tim-mossholder-C8jNJslQM3A-unsplash-1.jpg"
            alt="People at Work closes on 2 October. Your obligations don't."
            width={2000}
            height={1333}
            className="w-full rounded-2xl object-cover"
            priority
          />
        </figure>

        <section>
          <p className="mt-10 text-base/7 text-gray-600 dark:text-gray-400">
            The{" "}
            <a
              href="https://www.peopleatwork.gov.au/"
              rel="noreferrer"
              className="font-semibold text-indigo-600 hover:text-indigo-500 dark:text-indigo-400 dark:hover:text-indigo-300"
              target="_blank"
            >
              People at Work
            </a>{" "}
            survey platform is being permanently decommissioned. Registrations for new organisations closed on 1 June
            2026, the last surveys had to launch by 1 July, and on 2 October the platform shuts down and organisational
            data is removed.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            Around 5,000 Australian businesses used it, covering more than 160,000 workers. If you were one of them, you
            have two jobs before October. Export what you have, and work out what replaces it.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            The second job is the one worth thinking about properly, because the reasons the platform is being retired
            say something useful about how psychosocial risk assessment has been done in this country, and why a survey
            once a year was never quite enough.
          </p>

          <h2 className="mt-12 text-3xl font-semibold tracking-tight text-pretty text-gray-900 dark:text-white">
            First, export your reports
          </h2>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            Only the reports generated by the platform can be extracted. Raw survey data is not available for download,
            and everything else is deleted when the platform closes.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            If your People at Work reports form part of how you would demonstrate that you assessed psychosocial risk,
            they currently exist in one place and that place is closing. The Queensland Office of Industrial Relations
            has published guidance on exporting. Do it this month rather than in late September, when everyone else will
            be doing the same thing.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            While you are at it, note what you cannot take with you. Your response-level data goes. Your ability to
            compare this year against last year goes. Whatever benchmarking you had against other organisations goes.
            That loss is worth sitting with for a moment, because it points at something about how the record was being
            kept.
          </p>

          <h2 className="mt-12 text-3xl font-semibold tracking-tight text-pretty text-gray-900 dark:text-white">
            Nothing about your duty has changed
          </h2>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            Worth stating plainly, because it is the first question most employers ask. Regulators have been explicit
            that removing the platform does not reduce anyone&apos;s obligations. The psychosocial provisions in{" "}
            <Link
              href="psychosocial-risk-at-work-what-australian-employers-need-to-know/"
              className="font-semibold text-indigo-600 hover:text-indigo-500 dark:text-indigo-400 dark:hover:text-indigo-300"
            >
              WHS regulations
            </Link>{" "}
            across Australian states and territories are unchanged. What has gone away is a free tool many employers
            used to meet them, not the requirement itself.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            If anything, the guidance accompanying the closure has been clearer than usual on one point: managing
            psychosocial risk is an ongoing duty, not a one-off activity or a single survey event.
          </p>

          <h2 className="mt-12 text-3xl font-semibold tracking-tight text-pretty text-gray-900 dark:text-white">
            Why the platform is being retired
          </h2>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            Three reasons have been given, and each of them is instructive.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            <strong className="font-semibold text-gray-900 dark:text-white">Coverage.</strong> The tool needed
            modification to fully address the hazards described in the Model Code of Practice, particularly sexual
            harassment and isolated or remote work. That is not a small gap. It is also a structural problem rather than
            a fixable one, because a periodic survey is a poor instrument for catching either. Harassment does not wait
            for the survey window, and a worker who is isolated is precisely the worker least likely to be captured in
            an organisation-wide snapshot.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            <strong className="font-semibold text-gray-900 dark:text-white">Response rates.</strong> Recent survey
            cycles showed declining engagement. This is the quiet problem with long instruments. A 60-item survey is
            more rigorous than a short one in theory, and considerably less rigorous in practice when only a third of
            your workforce finishes it. The people who drop out are not a random sample either. The most overloaded,
            most disengaged and most at-risk employees are the least likely to spend twenty minutes on a questionnaire
            about how overloaded and disengaged they feel.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            <strong className="font-semibold text-gray-900 dark:text-white">It had been overtaken.</strong> The research
            and the regulatory framework moved on from where the tool was built.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            None of that is a criticism of People at Work, which did useful work for a decade and was free, which is
            more than most of the market managed. But taken together, the three reasons describe the limits of the
            annual survey model itself rather than the limits of one particular survey.
          </p>

          <h2 className="mt-12 text-3xl font-semibold tracking-tight text-pretty text-gray-900 dark:text-white">
            The problem with once a year
          </h2>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            Think about what an annual assessment actually produces.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            It gives you one data point per year. If something changes in March, you find out in November, assuming the
            person it affected is still there to tell you. Most of the time they are not, because the average tenure of
            a genuinely unhappy employee is shorter than your survey cycle.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            It gives you no sense of frequency. A hazard identified once looks the same in your report as a hazard
            occurring every week. Those are different risks requiring different responses, and a snapshot cannot tell
            them apart.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            It gives you no trend. You cannot see whether the workload problem in operations is getting worse or
            resolving itself, only that it was present on the day you asked.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            And it produces a document rather than a record. This is the part that matters most, and it is the part
            employers usually discover at the worst possible moment. A report tells you what you found. It does not tell
            you what you did about it. When someone asks you to account for a psychosocial hazard, and eventually
            someone will, the question is never just whether you knew. It is what happened next.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            The awkward truth about a filed survey report is that it is evidence you identified a problem. On its own,
            with no record of the response, that is not obviously better than never having asked.
          </p>

          <h2 className="mt-12 text-3xl font-semibold tracking-tight text-pretty text-gray-900 dark:text-white">
            What continuous assessment looks like
          </h2>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            The alternative is not a longer survey. It is a shorter one, more often.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            A check-in that takes under a minute gets completed by most of the workforce rather than a third of it. Run
            fortnightly or monthly, it produces twenty or more data points a year instead of one. That is enough to see
            which hazards are present, how often they occur, which teams they cluster in, and whether they are
            improving.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            Pair that with a channel people can use at any time, not only when a survey is open, and the hazards that
            periodic instruments miss start showing up: harassment when it happens, isolated workers when they are
            struggling, the problem that emerges three weeks after the annual survey closed.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            Then log the response. Every hazard identified, the action taken, the outcome, with a date attached. That is
            the difference between a report and a risk register, and it is the thing that answers the question you will
            actually be asked.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            Individually, a short check-in is not an assessment. It is one data point. The assessment is what
            accumulates: the pattern across weeks and months, at the organisational level, which is the level your duty
            applies at anyway.
          </p>

          <h2 className="mt-12 text-3xl font-semibold tracking-tight text-pretty text-gray-900 dark:text-white">
            What to do between now and October
          </h2>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            <strong className="font-semibold text-gray-900 dark:text-white">Export your reports.</strong> This month,
            not next.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            <strong className="font-semibold text-gray-900 dark:text-white">Decide what replaces it.</strong> Whether
            that is another platform, a consultant engagement or something you run internally, the gap between October
            and whenever you next assess is a gap in your record.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            <strong className="font-semibold text-gray-900 dark:text-white">
              Write down what you did about last year&apos;s findings.
            </strong>{" "}
            If your People at Work results identified hazards and you acted on them, that action is probably documented
            nowhere. Reconstructing it now, while people still remember, is worth an afternoon.
          </p>

          <p className="mt-6 text-base/7 text-gray-600 dark:text-gray-400">
            <strong className="font-semibold text-gray-900 dark:text-white">Set a cadence rather than a date.</strong>{" "}
            The single most useful change most employers can make is moving from an annual event to a continuous one. It
            is also the change the regulators have been signalling for a while.
          </p>

          <hr className="mt-12 border-gray-200 dark:border-gray-800" />

          <p className="mt-6 text-base/7 text-gray-600 italic dark:text-gray-400">
            <strong className="font-semibold text-gray-900 dark:text-white">HowsWork</strong> is a continuous
            psychosocial risk assessment platform for Australian employers. Anonymous check-ins and concern reports feed
            a risk register that records every hazard and the action taken.{" "}
            <Link
              href="/contact/demo"
              className="font-semibold text-indigo-600 hover:text-indigo-500 dark:text-indigo-400 dark:hover:text-indigo-300"
            >
              Request a demo
            </Link>
            .
          </p>
        </section>
      </article>
    </main>
  );
}
